[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.20"

# Allow Foundry scripts to read/write files
fs_permissions = [{ access = "read-write", path = "./" }]

[rpc_endpoints]
anvil = "http://127.0.0.1:8545"
base_sepolia = "https://sepolia.base.org"

[etherscan]
base_sepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }
